[package]
name = "ml_viz"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Michael A. Wright"]

[workspace]
members = ["yew-app", "scene"]

[dependencies]
ml_viz_scene = { path = "scene" }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
tera = "1"

[dev-dependencies]
serde_json = "1"
tiny_http = "0.12"

[[example]]
name = "ml-test-scene"
path = "examples/ml_test_scene.rs"
